# Generated by Django 5.1.3 on 2024-11-23 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_is_active_alter_student_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
    ]
